### DISCUSSION TITLE
DefectDojo doesnt work in helm installation to k8s cluster

### DISCUSSION THREAD

**Discussion by ep4sh** [DefectDojo/django-DefectDojo#8808] [Q&A] [answered]
Dear community, could you please advise what's wrong with my setup?
I am using helm install into k8s cluster, pods are running, health checks are OK.

I've create an ingress on my host, double-checked that domain in `ALLOWED_HOSTS`, but still getting an error, when accessing it:
```
uwsgi [10/Oct/2023 11:13:32] INFO [dojo.models:4101] enabling audit logging
uwsgi /app/dojo/reports/views.py:746: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi /app/dojo/engagement/views.py:1223: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi System check identified some issues:
uwsgi 
uwsgi WARNINGS:
uwsgi ?: (staticfiles.W004) The directory '/app/components/node_modules' in the STATICFILES_DIRS setting does not exist.
uwsgi 
uwsgi System check identified 1 issue (0 silenced).
uwsgi *** Starting uWSGI 2.0.21 (64bit) on [Tue Oct 10 11:13:33 2023] ***
uwsgi compiled with version: 10.2.1 20210110 on 29 May 2023 18:40:40
uwsgi os: Linux-5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023
uwsgi nodename: defectdojo-django-85594f7f4f-drsxj
uwsgi machine: x86_64
uwsgi clock source: unix
uwsgi detected number of CPU cores: 8
uwsgi current working directory: /app
uwsgi detected binary path: /usr/local/bin/uwsgi
uwsgi !!! no internal routing support, rebuild with pcre support !!!
uwsgi *** WARNING: you are running uWSGI without its master process manager ***
uwsgi your memory page size is 4096 bytes
uwsgi detected max file descriptor number: 1048576
uwsgi lock engine: pthread robust mutexes
uwsgi thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi uWSGI http bound on 0.0.0.0:8081 fd 3
uwsgi spawned uWSGI http 1 (pid: 14)
uwsgi uwsgi socket 0 bound to UNIX address /run/defectdojo/uwsgi.sock fd 6
uwsgi Python version: 3.11.3 (main, Apr 12 2023, 06:33:21) [GCC 10.2.1 20210110]
uwsgi Python main interpreter initialized at 0x7f909a47e558
uwsgi python threads support enabled
uwsgi your server socket listen backlog is limited to 100 connections
uwsgi your mercy for graceful operations on workers is 60 seconds
uwsgi mapped 183136 bytes (178 KB) for 4 cores
uwsgi *** Operational MODE: preforking+threaded ***
uwsgi [10/Oct/2023 11:13:35] INFO [dojo.models:4101] enabling audit logging
uwsgi WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f909a47e558 pid: 1 (default app)
uwsgi *** uWSGI is running in multiple interpreter mode ***
uwsgi spawned uWSGI worker 1 (pid: 1, cores: 2)
uwsgi spawned uWSGI worker 2 (pid: 15, cores: 2)
uwsgi /app/dojo/reports/views.py:746: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi /app/dojo/engagement/views.py:1223: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi [uwsgi-http key: defectdojo.<REDACTED>.com client_addr: 10.101.135.1 client_port: 65127] hr_read(): Connection reset by peer [plugins/http/http.c line 918]
uwsgi [pid: 1|app: -|req: -/-] 10.101.135.1 (-) {30 vars in 415 bytes} [Tue Oct 10 11:15:39 2023] GET /login?force_login_form&next=/ => generated 15486 bytes in 1933 msecs (HTTP/1.1 200) 10 headers in 489 bytes (1 switches on core 0)
uwsgi [pid: 1|app: -|req: -/-] 10.101.135.1 (-) {34 vars in 416 bytes} [Tue Oct 10 11:15:39 2023] GET /uwsgi_health => generated 15486 bytes in 1933 msecs (HTTP/1.1 200) 10 headers in 489 bytes (1 switches on core 1)
uwsgi [pid: 1|app: -|req: -/-] 10.101.135.1 (-) {34 vars in 417 bytes} [Tue Oct 10 11:15:49 2023] GET /uwsgi_health => generated 15486 bytes in 118 msecs (HTTP/1.1 200) 10 headers in 489 bytes (1 switches on core 0)
nginx Basic auth is on for user ...
uwsgi /app/dojo/reports/views.py:746: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi /app/dojo/engagement/views.py:1223: DeprecationWarning: invalid escape sequence '\?'
uwsgi   path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
uwsgi [uwsgi-http key: defectdojo.<REDACTED>.com client_addr: 10.101.135.1 client_port: 35382] hr_read(): Connection reset by peer [plugins/http/http.c line 918]
uwsgi [pid: 15|app: -|req: -/-] 10.101.135.1 (-) {30 vars in 415 bytes} [Tue Oct 10 11:15:49 2023] GET /login?force_login_form&next=/ => generated 15486 bytes in 1753 msecs (HTTP/1.1 200) 10 headers in 489 bytes (1 switches on core 0)
```

But it works (veeeeeeeery slow) when I use k8s port-forward.
My configMap:
```
apiVersion: v1
data:
  DD_ADMIN_FIRST_NAME: Admin
  DD_ADMIN_LAST_NAME: User
  DD_ADMIN_MAIL: admin@defectdojo.local
  DD_ADMIN_USER: admin
  DD_ALLOWED_HOSTS: defectdojo.<REDACTED>.com,localhost,*
  DD_CELERY_BROKER_HOST: rc1b-<REDACTED>.net
  DD_CELERY_BROKER_PARAMS: ""
  DD_CELERY_BROKER_PATH: //
  DD_CELERY_BROKER_PORT: "6379"
  DD_CELERY_BROKER_SCHEME: redis
  DD_CELERY_BROKER_USER: ""
  DD_CELERY_LOG_LEVEL: INFO
  DD_CELERY_WORKER_AUTOSCALE_MAX: ""
  DD_CELERY_WORKER_AUTOSCALE_MIN: ""
  DD_CELERY_WORKER_CONCURRENCY: ""
  DD_CELERY_WORKER_POOL_TYPE: solo
  DD_CELERY_WORKER_PREFETCH_MULTIPLIER: ""
  DD_DATABASE_ENGINE: django.db.backends.postgresql
  DD_DATABASE_HOST: c-<REDACTED>.net
  DD_DATABASE_NAME: defectdojo
  DD_DATABASE_PORT: "5432"
  DD_DATABASE_USER: defectdojo
  DD_DJANGO_METRICS_ENABLED: "false"
  DD_INITIALIZE: "true"
  DD_SITE_URL: https://defectdojo.<REDACTED>.com
  DD_UWSGI_ENDPOINT: /run/defectdojo/uwsgi.sock
  DD_UWSGI_HOST: localhost
  DD_UWSGI_NUM_OF_PROCESSES: "2"
  DD_UWSGI_NUM_OF_THREADS: "2"
  DD_UWSGI_PASS: unix:///run/defectdojo/uwsgi.sock
  METRICS_HTTP_AUTH_USER: monitoring
  NGINX_METRICS_ENABLED: "false"
kind: ConfigMap

```
