### ISSUE TITLE
Env file didn't work (partially)

### ISSUE THREAD

**Issue by Mozartuss** [DefectDojo/django-DefectDojo#10467]
I use DefectDojo in release mode with self build docker container and https configuration. For the config, I use the mysql-rabbitmq.env file, Then I make a link to the dojo/settings/.env.prod file. 
The problem is that the config is only read partially, the port and url settings works fine. But everything after the Initializer section didn't work. It works perfectly if I write the same env variables directly in the docker-compose.yml file.

I also slightly modify the dc-build.sh script, so that the correct env file is used
```zsh
docker compose --profile mysql-rabbitmq --env-file ./docker/environments/mysql-rabbitmq.env build
```

```.env
DD_DATABASE_URL=mysql://defectdojo:defectdojo@mysql:3306/defectdojo?charset=utf8mb4
DD_DATABASE_ENGINE=django.db.backends.mysql
DD_DATABASE_HOST=mysql
DD_DATABASE_PORT=3306

DD_DATABASE_NAME=defectdojo
DD_DATABASE_USER=defectdojo
DD_DATABASE_PASSWORD=defectdojo

DD_TEST_DATABASE_NAME=test_defectdojo
DD_TEST_DATABASE_URL=mysql://defectdojo:defectdojo@mysql:3306/test_defectdojo?charset=utf8mb4

DD_CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

DD_DOCKERCOMPOSE_DATABASE=mysql
DD_DOCKERCOMPOSE_BROKER=rabbitmq

# Setup NGINX
DD_PORT=80
DD_TLS_PORT=443
DD_SITE_URL={url}


# USWGI - CELERYBEAT - CELERYWORKER - INITIALIZER

DD_DJANGO_METRICS_ENABLED=false

# INITIALIZER

DD_ADMIN_USER=Admin
DD_ADMIN_FIRST_NAME={first name}
DD_ADMIN_LAST_NAME={last name}
DD_ADMIN_MAIL={e-mail}

# Gitlab

DD_SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED=True
DD_SOCIAL_AUTH_GITLAB_PROJECT_AUTO_IMPORT=True

DD_SOCIAL_AUTH_GITLAB_KEY='{key}'
DD_SOCIAL_AUTH_GITLAB_SECRET='{secret}'
DD_SOCIAL_AUTH_GITLAB_API_URL='{url}'
#related issue: [Oauth Gitlab] GITLAB_PROJECT_AUTO_IMPORT fails because of 403 insufficient_scope #8434
DD_SOCIAL_AUTH_GITLAB_SCOPE=['api', 'read_user', 'openid']


DD_INITIALIZE=False # ensures that db remains unchangend when re-running defectdojo
DD_INITIALIZE=True # ONLY ON FIRST START
```

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 24.04 LTS
 - DefectDojo version: 2.35.4

**Comment by mtesauro** [comment]
Just a heads up that as of the release today (2.36.0) DefectDojo is deprecating RabbitMQ and there will be a PR to simplify the docker-compose files for only PostgreSQL and Redis. We can look at .env file handling at that time. I don't know of anything done to prevent that working FWIW.

To get info on the deprecation of RabbitMQ, look at these discussions:
https://github.com/DefectDojo/django-DefectDojo/discussions?discussions_q=author%3Amtesauro
especially:
https://github.com/DefectDojo/django-DefectDojo/discussions/9690

If  you happen to be using MySQL as well, there's a discussion on migrating to PostgreSQL as well at https://github.com/DefectDojo/django-DefectDojo/discussions/9480

**Comment by Mozartuss** [comment]
Thanks for the information, I switched to postgres and redis. 👍 
I solved the problem by editing the `docker-compose` file and add this lines to the `uwsgi`, `celerybeat`, `celeryworker` sections:

```yaml

enviroment:
    ...
    DD_SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED: "${DD_SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED:-false}"
    DD_SOCIAL_AUTH_GITLAB_PROJECT_AUTO_IMPORT: "${DD_SOCIAL_AUTH_GITLAB_PROJECT_AUTO_IMPORT:-false}"
    DD_SOCIAL_AUTH_GITLAB_KEY: "${DD_SOCIAL_AUTH_GITLAB_KEY:-}"
    DD_SOCIAL_AUTH_GITLAB_SECRET: "${DD_SOCIAL_AUTH_GITLAB_SECRET:-}"
    DD_SOCIAL_AUTH_GITLAB_API_URL: "${DD_SOCIAL_AUTH_GITLAB_API_URL:-}"
    DD_SOCIAL_AUTH_GITLAB_SCOPE: "${DD_SOCIAL_AUTH_GITLAB_SCOPE:-}"
```
