### ISSUE TITLE
DefectDojo containers only function when group is 0 (root)

### ISSUE THREAD

**Issue by corang** [DefectDojo/django-DefectDojo#11031]
**Bug description**
When running the defectdojo-nginx and defectdojo-django (celery-worker) containers in a secured cluster (root not allowed) they fail to start

**Steps to reproduce**
1. Deploy helm chart on kubernetes with podSecurityContext and containerSecurityContext for all pods/containers set to

```yaml
securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
```

**Expected behavior**
Helm chart deploys successfully and defectdojo comes up healthy

**Deployment method**
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: k3d 1.29.6+k3s2
 - DefectDojo version : 2.38.4

**Logs** 


celery-worker:
```
uid=1001(defectdojo) gid=1001 groups=1001                                                                                                                  
[09/Oct/2024 18:51:34] INFO [dojo.models:4572] enabling audit logging                                                                                      
Waiting for database to be reachable                                                                                                                       
[09/Oct/2024 18:51:36] INFO [dojo.models:4572] enabling audit logging                                                                                      
System check identified no issues (0 silenced).                                                                                                            
[09/Oct/2024 18:51:39] INFO [dojo.models:4572] enabling audit logging                                                                                      
/usr/local/lib/python3.11/site-packages/celery/platforms.py:799: SecurityWarning: An entry for the specified gid or egid was not found.                    
We're assuming this is a potential security issue.                                                                                                         
                                                                                                                                                           
  warnings.warn(SecurityWarning(ASSUMING_ROOT))                                                                                                            
Running a worker with superuser privileges when the                                                                                                        
worker accepts messages serialized with pickle is a very bad idea!                                                                                         
                                                                                                                                                           
If you really want to continue then you have to set the C_FORCE_ROOT                                                                                       
environment variable (but please think about this before you do).                                                                                          
                                                                                                                                                           
User information: uid=1001 euid=1001 gid=1001 egid=1001
```

defectdojo-nginx
```
sed: can't create temp file '/etc/nginx/nginx.confXXXXXX': Permission denied                                                                               
Nginx metrics are enabled                                                                                                                                  
sed: can't create temp file '/etc/nginx/nginx.confXXXXXX': Permission denied                                                                               
/entrypoint-nginx.sh: line 30: can't create /etc/nginx/.htpasswd: Permission denied                                                                        
Basic auth is on for user ...                                                                                                                              
2024/10/09 18:51:19 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)                                                     
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

**Additional context** (optional)
I'm not sure whats going on with the celery worker but the defectdojo-nginx container has the majority of its filesystem owned by root

**Comment by d-mankowski-synerise** [comment]
The minimal working permissions that I managed to get DD working are as follows:

```yaml
securityContext:
  djangoSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
  nginxSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
      add:
        - CHOWN
        - SETGID
        - SETUID
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
```
