### ISSUE TITLE
Symlink error on helm chart when deployed via argocd

### ISSUE THREAD

**Issue by RyuunosukeDS3** [DefectDojo/django-DefectDojo#11893]
**Bug description**
When trying to deploy defect dojo using argocd pointing to this repo it displays the followin error:

argocd app create --upsert -f homolog/defectdojo/application.yaml
163time="2025-02-24T13:20:06-03:00" level=fatal msg="rpc error: code = InvalidArgument desc = application spec for defectdojo-homolog-devops is invalid: InvalidSpecError: Unable to generate manifests in helm/defectdojo: rpc error: code = Unknown desc = failed to build helm dependencies: failed to build dependencies: failed to get command args to log: `helm dependency build` failed signal: killed: walk.go:74: found symbolic link in path: <path to cached source>/helm/defectdojo/README.md resolves to <path to cached source>/readme-docs/KUBERNETES.md. Contents of linked file included and used%0APulled: registry-1.docker.io/bitnamicharts/postgresql:16.4.5%0ADigest: sha256:7e2bd8ed9d2ac7673a5730141301d038fa7b7cf130503c8dd5dcbc6ddfe0e377"

seems to be related with:

https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#out-of-bounds-symlinks-now-blocked-at-fetch

**Steps to reproduce**
1. Create an application on ArgoCD for DefectDojo
2. Run argocd app create --upsert defectdojo-application.yaml

**Expected behavior**
It should simply render the helm chart

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.02
 - DefectDojo version (see footer) or commit message: v2.43.4

**Logs** 
```
163time="2025-02-24T13:20:06-03:00" level=fatal msg="rpc error: code = InvalidArgument desc = application spec for defectdojo-homolog-devops is invalid: InvalidSpecError: Unable to generate manifests in helm/defectdojo: rpc error: code = Unknown desc = failed to build helm dependencies: failed to build dependencies: failed to get command args to log: `helm dependency build` failed signal: killed: walk.go:74: found symbolic link in path: <path to cached source>/helm/defectdojo/README.md resolves to <path to cached source>/readme-docs/KUBERNETES.md. Contents of linked file included and used%0APulled: registry-1.docker.io/bitnamicharts/postgresql:16.4.5%0ADigest: sha256:7e2bd8ed9d2ac7673a5730141301d038fa7b7cf130503c8dd5dcbc6ddfe0e377"
```

**Comment by kiblik** [comment]
Can you please show your `homolog/defectdojo/application.yaml` definition?

**Comment by RyuunosukeDS3** [comment]
Sure, here it goes:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo-homolog-devops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homolog-devops
  destination:
    server: "server-url"
    namespace: homolog
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: git@our-git-repo:devops/prod-devops.git
      path: homolog/defectdojo/k8s
      targetRevision: main
    - repoURL: git@our-git-repo:devops/prod-devops.git
      targetRevision: main
      ref: charts
    - repoURL: https://github.com/DefectDojo/django-DefectDojo.git
      targetRevision: 2.40.3
      path: helm/defectdojo
      helm:
        releaseName: defectdojo
        valueFiles:
          - $charts/homolog/defectdojo/helm/defectdojo-values.yaml

```

**Comment by kiblik** [comment]
I would try not to point to `https://github.com/DefectDojo/django-DefectDojo.git` but use `https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts`, how it is described in https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/KUBERNETES.md#helm-chart.
Be aware that it uses different versioning (e.g. last app version is `2.43.4` but helm chart is `1.6.175`).

Or use dependencies: Define your own `Chart.yaml` and you do not need to mention it in `application.yaml` anymore.
```yaml
---
apiVersion: v2
name: my-dd
description: A Helm chart for Kubernetes to install my DefectDojo
type: application
version: 0.0.30
dependencies:
  - name: defectdojo
    version: 1.6.175
    repository: "https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts"
```

but be aware that your values in `values.yaml` for DD needs to be defined like:
```yaml
defectdojo:
  createSecret: true
  extraConfigs:
    DD_...
  extraSecrets:
    DD_...
```

**Comment by RyuunosukeDS3** [comment]
Importing as a dependency worked! Thanks for your help.

**Comment by kiblik** [comment]
> [@kiblik](https://github.com/kiblik) [@RyuunosukeDS3](https://github.com/RyuunosukeDS3) I'm also stuck up here, I have been using Dependency Chat which worked well, but I'm trying to use external Redis and RDS for this, but seem like my custom values are not getting effected.

With the Dependency charts, the most often issue is wrong indentation (the right number of spaces). Compared to the original `values.yaml` file, you need to put all values to the right (2 or 4 or any number which is nice for you).

One more note, if you are disabling redis/psql be aware that you need to set some specific values as well. Check: https://github.com/DefectDojo/django-DefectDojo/issues/11829#issuecomment-2754860885

**Comment by mazmar** [comment]
I've managed to get this to work without using the dependency

when switching from 
`https://github.com/DefectDojo/django-DefectDojo.git`
to
`https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts`

don't forget to change `path` to  `chart` in the helm


final application should look like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: defectdojo
spec:
  project: defectdojo
  destination:
    namespace: "dojo"
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://myrepo/repo.git'
      ref: values
    - repoURL: 'https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts'
      targetRevision: 1.6.181
      chart: defectdojo
      helm:
        valueFiles:
          - $values/defectdojo/values.yaml
```

this now works as expected
