### ISSUE TITLE
[Proposal] Helm `requirements.yaml` could use aliased repositories

### ISSUE THREAD

**Issue by carlosjgp** [DefectDojo/django-DefectDojo#1728]
**Is your feature request related to a problem? Please describe**
It's a feature request since it's not blocking us but it takes this deployment out of our desire workflow.

The Helm `requirements.yaml` is using hardcoded URLs to fetch child charts but we want to use our proxy cache system this could be Nexus, Artifactory, Harbor, CharMuseum,...

**Describe the solution you'd like**
Helm `requirements.yaml` support [named repositories](https://werf.io/documentation/reference/deploy_process/working_with_chart_dependencies.html) instead (`@stable`)

In this way, we can define which is the upstream for `@stable`. This will be a security improvement for use since we are in control of where the charts come from

The `requirements.yaml` would look like this
```
dependencies:
  - name: mysql
    version: 0.15.0
    repository: "@stable"
    condition: mysql.enabled
  - name: postgresql
    version: 3.11.7
    repository: "@stable"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 4.3.1
    repository: "@stable"
    condition: rabbitmq.enabled
  - name: redis
    version: 6.1.4
    repository: "@stable"
    condition: redis.enabled
```

**Describe alternatives you've considered**

**Additional context**
