### ISSUE TITLE
Celery should not be started with --uid in docker

### ISSUE THREAD

**Issue by uncycler** [DefectDojo/django-DefectDojo#2922]
**Bug description**
When celery is started with "--uid" argument, it needs root access. In docker, it superfluous since the Dockerfile.django already start the process with the good uid. This cause issue when starting celery-beat in K8s with a securityContext.

**Steps to reproduce**
1. Deploy django image with celery beat entrypoint in K8s with securityContext:
```yaml
securityContext:
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
```
2. When python try to change uid, you'll get a permission denied error.,

**Expected behavior**
Celery should no try changing uid since it's Dockerfile-django already set the good uid.

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash
