### ISSUE TITLE
Can DD_ALLOWED_HOSTS be set as "*" ?

### ISSUE THREAD

**Issue by Homopatrol** [DefectDojo/django-DefectDojo#4190]
**Bug description**
I've run Into some issues whilst deploying Defectdojo v `1.14.0` After deploying the k8s healthchecks began failing which stopped the nginx container as being marked as ready.

From running `oc describe` for the defectdojo-django pod the events show the healthcheck failing:
```
  Warning  Unhealthy       1h (x3 over 1h)     kubelet, 10.112.78.50  Readiness probe failed: Get "http://172.30.240.138:8080/uwsgi_health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff         33m (x92 over 1h)   kubelet, 10.112.78.50  Back-off restarting failed container
  Warning  Unhealthy       13m (x161 over 1h)  kubelet, 10.112.78.50  Readiness probe failed: HTTP probe failed with statuscode: 502
  Warning  Unhealthy       8m (x310 over 1h)   kubelet, 10.112.78.50  Readiness probe failed: HTTP probe failed with statuscode: 400
  Warning  Unhealthy       3m (x120 over 1h)   kubelet, 10.112.78.50  Liveness probe failed: HTTP probe failed with statuscode: 400
```
We had set  `DD_ALLOWED_HOSTS: 'localhost' ` in our ConfigMap,  we changed this to be` "*"` this fixed the issue.

My question is - is it acceptable to set `DD_ALLOWED_HOSTS `as` "*"` ?

**Steps to reproduce**
1.Deploy Defect Dojo via Kubernetes and helm charts

**Expected behavior**
I expected both pods to start up without issue

**Deployment method** *(select with an `X`)*
- [x] k8s/OpenShift with Helm chart
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
configMap  
```
apiVersion: v1
data:
  C_FORCE_ROOT: "true"
  DD_ADMIN_FIRST_NAME: Admin
  DD_ADMIN_LAST_NAME: User
  DD_ADMIN_MAIL: admin@defectdojo.local
  DD_ADMIN_USER: admin
  DD_ALLOWED_HOSTS: 'localhost'    
```

**Additional Information* (optional)

Additionally we found the logs for the nginx container show 
```
2021/04/01 16:20:08 [error] 10#10: *604 "/etc/nginx/html/nginx_status/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /nginx_status/ HTTP/1.1", host: "localhost:8080"
```
howeverr from running `cat /etc/nginx/nginx.conf` inside the nginx container we can see :
```
    # Used by Kuebernetes readiness checks
    location = /uwsgi_health {
      limit_except GET { deny all; }
      rewrite /.+ /login?next=/ break;
      include /run/defectdojo/uwsgi_pass;
      include /etc/nginx/wsgi_params;
      access_log off;
    }
    ```
So Why are we getting this error log?

**Comment by madchap** [comment]
You can, probably exposing yourself to potential poisoning issues. See maybe https://stackoverflow.com/questions/25018250/what-is-the-vulnerability-allowed-hosts-is-defending-against for some info.

I run defectdojo on k8s (GKE), and I just specified the hosts, should work for you too.

Looks like `defectdojo.domain.com,defectdojo-django.defectdojo.svc.cluster.local` on my side.

**Comment by Homopatrol** [comment]
If you are deploying via Helm charts then you don't have to know all these hosts at install time?

Futhermore, the `host` value is used for healthchecks which I don't think is compatible.

`host` is used in django-deployment.yaml here
```
....
        - name: DD_CELERY_BROKER_PASSWORD
....
        livenessProbe:
          httpGet:
            path: /login?next=/
            port: http
            httpHeaders:
            - name: Host
              value: {{ .Values.host }}
....
      - name: nginx
....
       livenessProbe:
          httpGet:
            path: /nginx_health
            port: http
            {{- if .Values.django.nginx.tls.enabled }}
            scheme: HTTPS
            {{- end }}
            httpHeaders:
            - name: Host
              value: {{ .Values.host }}
......
```
thus we cannot change this value at deploy-time without impacting it.


With the default configurations - configmap.yaml 
```
data:
  C_FORCE_ROOT: "{{ .Values.celery.worker.force_root | default false }}"
  ...
  DD_ALLOWED_HOSTS: {{ .Values.host }}
  ...
  DD_DATA_UPLOAD_MAX_MEMORY_SIZE: "20971520"
```
values.yaml
```
...
host: defectdojo.<cluster>.eu-gb.containers.appdomain.cloud
imagePullPolicy: IfNotPresent
...
```
Causes the healthcheck failed stopped the nginx container as being marked as ready.

However setting a value `ddhost:”*” ` and using applying this to `DD_ALLOWED_HOSTS: ` in the configmap in meant the healthcheck to worked as expected and nginx was able to start.

configmap.yaml
```
data:
  C_FORCE_ROOT: "{{ .Values.celery.worker.force_root | default false }}"
  ...
  DD_ALLOWED_HOSTS: "{{ .Values.ddHost }}"
  ...
  DD_DATA_UPLOAD_MAX_MEMORY_SIZE: "20971520"
```
values.yaml
```
...
ddHost: "*"
host: localhost
imagePullPolicy: IfNotPresent
...
```
