### ISSUE TITLE
Authentication via SAML2 with helm file

### ISSUE THREAD

**Issue by nareshbogathi** [DefectDojo/django-DefectDojo#5114]
Hi 

I am planning to use SAML2 for Defectdojo SSO with Yaml, Can you please help me to share some example code?
I am using like this, but it's failing in helm deployment
```

extraConfigs:
  DD_SAML2_ENABLED: 'true'
  # If the metadata can be accessed from a url, try the
  DD_SAML2_METADATA_AUTO_CONF_URL: ${{ parameters.SAML2MetadataURL }}
  # Otherwise, downlaod a copy of the metadata into an xml file, and
  # list the path in DD_SAML2_METADATA_LOCAL_FILE_PATH
  # DD_SAML2_METADATA_LOCAL_FILE_PATH: '/path/to/your/metadata.xml'

  DD_SAML2_ATTRIBUTES_MAP: { Email: email, Username: user_name, Firstname: first_name, Lastname: last_name }
```
It's giving validation error
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ConfigMap.data.DD_SAML2_ATTRIBUTES_MAP): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"`

Can someone please help me with correct syntax
