### ISSUE TITLE
Move away from HELM 2

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#5459]
Currently DD helm deployment uses V1 specification (Helm 2):

```
apiVersion: v1
appVersion: "2.4.1"
description: A Helm chart for Kubernetes to install DefectDojo
name: defectdojo
version: 1.6.22
icon: https://www.defectdojo.org/img/favicon.ico
maintainers:
  - name: madchap
    email: defectdojo-project@owasp.org
    url: https://github.com/DefectDojo/django-DefectDojo
```

Helm 2 is not under  support anymore:
https://helm.sh/blog/helm-v2-deprecation-timeline/

It would be nice that product move away from helm 2 to helm 3. 

Some notes about the migration https://helm.sh/docs/topics/v2_v3_migration/
