### ISSUE TITLE
SAML session ending does not end defectdojo session

### ISSUE THREAD

**Issue by mircea-pavel-anton** [DefectDojo/django-DefectDojo#5856]
**Bug description**

When using SAML2 for authentication via Keycloak, ending the keycloak session does not end the defectdojo session as well.

As such, if one user logs in to keycloak and then uses SAML2 to authenticate on defectdojo, then logs out, the next person to try to access defectdojo on that same computer will already be logged in with the former users account.

**Steps to reproduce**

> the following steps assume you already have a keycloak instance deployed

1.  Create a new Keycloak Client
  - Client ID: defectdojo
  - Enabled: true
  - Client Protocol: saml
  - Include AuthnStatement: ON
  - Sign Documents: ON
  - Sign Assertions: ON
  - Base URL: "https://<your keycloak url>/"
  - Root URL: "https://<your keycloak url>/"
  - Valid Redirect URIs:
        - "https:// < your defectdojo url > /*"
  - Master SAML Processing URL: "https://< your defectdojo url>"
2. Configure DefectDojo helm chart with the following `extraConfig` entries:

  ``` yaml

extraConfigs:
  DD_ALLOWED_HOSTS: "*"
  DD_SITE_URL: "https://< defectdojo url >"
  DD_LOGIN_REDIRECT_URL: "https://< defectrojo url >"

  # SAML2 CONFIGURATION
  DD_SAML2_ENABLED: "True"
  DD_SAML2_LOGIN_BUTTON_TEXT: "Login with SAML"
  # DD_SAML2_LOGOUT_URL: "https://< defectdojo url >/saml2/ls/post/"
  DD_SAML2_LOGOUT_URL: "https://< keycloak url >/auth/realms/CI/protocol/saml"
  DD_SAML2_METADATA_AUTO_CONF_URL: "https://<keycloak url>/auth/realms/CI/protocol/saml/descriptor"
  DD_SAML2_ENTITY_ID: "defectdojo"
  DD_SAML2_CREATE_USER: "True"
  DD_SAML2_ATTRIBUTES_MAP: "'Email'='email', 'UserName'='username', 'Firstname'='firstName', 'Lastname'='lastName'"
  ```

> Note: I have tried both the `DD_SAML2_LOGOUT_URL` options presented above and they both give different errors when pressing the `SAML Logout`
> If redirected to the keycloak service, then keycloak claims a missing saml token, and i get an `invalid request` page  
> If redirected to the defectdojo service, then the following error is thrown: `No SAMLResponse or SAMLRequest parameter found`

3. Go to your defectdojo url and clock on the `Login with SAML` button
4. Log in with your keycloak credentials
5. From the keycloak ui, end the session for the user, or from another application with SSO integrated, simply log out
6. Go back to defectdojo and you are still logged in

Which would not necessarily be all that bad in itself, but the real issue is that if another user logs in via keycloak and tries to access defectdojo, they are still logged in as the previous user.

**Expected behavior**

Ending the keycloak session should also end the defectdojo session.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Kubernetes deployment via helm chart
 - DefectDojo version (see footer) or commit message:  2.4.1
