### ISSUE TITLE
SLO not working / not implemented for Native Keycloak Integration

### ISSUE THREAD

**Issue by mircea-pavel-anton** [DefectDojo/django-DefectDojo#5933]
**Bug description**

I have managed to get SSO working via Keycloak on my instance, but it seems that SLO is not working/not implemented.

While DefectDojo can use keycloak to authenticate, it seems that past that point, the 2 are not aware of each others state. Ending the keycloak session will not log out the defectdojo active user, and, similarly, logging out from defectdojo will not end the keycloak session.

**Steps to reproduce keycloak session ending not logging out defectdojo**:
1. Configure SSO via Keycloak as per the official docs
2. Go to your DefectDojo instance, and click on the `Login with Keycloak` button.
 
![image](https://user-images.githubusercontent.com/28601784/154496913-b809cd9f-980b-42cd-addb-77bb9f170df5.png)

3. At this point, you should be greeted by the dashboard

![image](https://user-images.githubusercontent.com/28601784/154497293-a5243981-8858-4e86-8d95-8d95067b85ef.png)

4. Go to your Keycloak admin panel, Go to clients, select your defectdojo client and then open the sessions tab. You should see the number of active session as being: 1

![image](https://user-images.githubusercontent.com/28601784/154498003-864865af-479e-4805-8262-da32ade88cbe.png)

5. From any other SSO-enabled app, or from keycloak itself, end that client's session.
6. Go back to your Keycloak admin page and see the active sessions count for the defectdojo client be 0

![image](https://user-images.githubusercontent.com/28601784/154498366-b9491f44-0ce3-4e92-8ffe-ad6118bea9ee.png)

7. Go to your defectdojo instance and see that you are still logged in, even though the session has ended.

**Steps to reproduce defectdojo logout not ending keycloak session**:
1. Configure SSO via Keycloak as per the official docs
2. Go to your DefectDojo instance, and click on the `Login with Keycloak` button.
 
![image](https://user-images.githubusercontent.com/28601784/154496913-b809cd9f-980b-42cd-addb-77bb9f170df5.png)

3. At this point, you should be greeted by the dashboard

![image](https://user-images.githubusercontent.com/28601784/154497293-a5243981-8858-4e86-8d95-8d95067b85ef.png)

4. Go to your Keycloak admin panel, Go to clients, select your defectdojo client and then open the sessions tab. You should see the number of active session as being: 1

![image](https://user-images.githubusercontent.com/28601784/154498003-864865af-479e-4805-8262-da32ade88cbe.png)

5. Go back to your DefectDojo instance and Log out:

![image](https://user-images.githubusercontent.com/28601784/154498911-1acb1389-85a2-49fc-b8ca-b013a0cfc17f.png)

![image](https://user-images.githubusercontent.com/28601784/154499397-78069281-7467-4e74-a056-1965fd21cd17.png)

6. In your keycloak panel, on the client page, in the active sessions tab, the number of active sessions is still 1:

![image](https://user-images.githubusercontent.com/28601784/154499456-e4243ddd-8d52-4fc6-8ccb-b4240ddd128e.png)

**Expected behavior**

Both apps should be aware of each others state. Ending the keycloak session should log me out of defectdojo and defectdojo logout should cause the keycloak session to end.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: 2.7.1 (chart version)

**Logs** 

No weird logs are thrown by the defectdojo-django pod nor by the keycloak pod.

**Additional context** (optional)

What I have tried:
  - Enabling front channel logout:
    - set `Front Channel Logout` to `true`
    - set `Front Channel Logout URL` to `https://defectdojo.your_domain_here/logout`
  - Enabling back channel logout:
    - set `Back Channel Logout URL` to `https://defectdojo.your_domain_here/logout`
    - set `Backchannel Logout Session Required` to `true`

I have taken a bit of a look at the python social auth plugin that is used in the SSO integration, and it seems that there should be a `REVOKE_TOKEN_URL` that *may* do that, but I don't see it being documented as working for the keycloak integration. I haven't looked into it much more past that point.

The `extraConfig` params given to my defectdojo instance:

``` yaml
  DD_SOCIAL_LOGIN_AUTO_REDIRECT: 'True'
  DD_SOCIAL_AUTH_SHOW_LOGIN_FORM: 'True'

  # Recommended settings for Keycloak SSO
  DD_SESSION_COOKIE_SECURE: 'True'
  DD_CSRF_COOKIE_SECURE: 'True'
  DD_SECURE_SSL_REDIRECT: 'True'

  # Keycloak SSO Config
  DD_SOCIAL_AUTH_KEYCLOAK_OAUTH2_ENABLED: 'True'
  DD_SOCIAL_AUTH_KEYCLOAK_KEY: "<keycloak_client_id>"
  DD_SOCIAL_AUTH_KEYCLOAK_SECRET: "<keycloak_client_secret>"
  DD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: 'https://<keycloak url>/auth/realms/<realm name>/protocol/openid-connect/auth'
  DD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: 'https://<keycloak url>/auth/realms/<realm name>/protocol/openid-connect/token'
  DD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: '<keycloak realm public key here>'
```

My keycloak client configuration:

**Main Configuration**:
![image](https://user-images.githubusercontent.com/28601784/154502218-d065765e-19b9-4d3b-8b21-c373190add06.png)

**Fine Grain Configuration**:
![image](https://user-images.githubusercontent.com/28601784/154502411-69e63f64-4056-46ea-8518-4c46b99c45c8.png)

**Mappers**:
![image](https://user-images.githubusercontent.com/28601784/154502511-597cdc4a-5d6a-4657-a6b4-fc9cca759276.png)
