### ISSUE TITLE
Keycloak login with self-signed certificate fails

### ISSUE THREAD

**Issue by maxnitze** [DefectDojo/django-DefectDojo#5954]
Hi,

I'm trying to enable Keycloak login. I'm installing DefectDojo with the Helm chart.

I added the following config:

```yaml
extraSecrets:
  DD_SESSION_COOKIE_SECURE: 'True'
  DD_CSRF_COOKIE_SECURE: 'True'
  DD_SECURE_SSL_REDIRECT: 'True'
  DD_SOCIAL_AUTH_KEYCLOAK_OAUTH2_ENABLED: 'True'
  DD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: '<PUBLIC_KEY>'
  DD_SOCIAL_AUTH_KEYCLOAK_KEY: 'defectdojo'
  DD_SOCIAL_AUTH_KEYCLOAK_SECRET: '1234asdf-...'
  DD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: 'https://keycloak.internal.company.com/auth/realms/my-realm/protocol/openid-connect/auth'
  DD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: 'https://keycloak.internal.company.com/auth/realms/my-realm/protocol/openid-connect/token'
```

The Keycloak instance is hosted internally and has a certificate signed by the companies CA. But not "officially". When I try to login I get the following error message:

```
Authentication failed: HTTPSConnectionPool(host='keycloak.internal.company.com', port=443): Max retries exceeded with url: /auth/realms/my-realm/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)'))) 
```

The thing I'm looking for here is basically something like `DD_SOCIAL_AUTH_KEYCLOAK_SSL_SKIP_VERIFY: 'True'`.

The only thing I could find was `REQUESTS_CA_BUNDLE` in the docs for the SAML logins (https://defectdojo.github.io/django-DefectDojo/dev/integrations/social-authentication/#saml-20). But it's only mentioned briefly and I don't even know what the value there should be (file reference? cert content? in base64?).

I also searched for documentation of the Python social auth plugin, that I suspect is used here. But I could not find anything in its documentation either.

Is there any documentation on this issue somewhere?

Thanks in advance!
