### ISSUE TITLE
Couldn't access findings page

### ISSUE THREAD

**Issue by abz89** [DefectDojo/django-DefectDojo#7009]
**Slack us first!**
This issue has already posted in [slack](https://owasp.slack.com/archives/C2P5BA8MN/p1666094292648589?thread_ts=1666094184.283119&cid=C2P5BA8MN)

**Bug description**
We often see 502 errors when opening findings related pages (e.g /finding/27394, /product/358/finding/*)

**Steps to reproduce**
1. Go to related finding pages
2. Page will loading in a few minutes
3. Error page "Error: Server Error. The server encountered a temporary error and could not complete your request. Please try again in 30 seconds" occurred

**Expected behavior**
Page will opened as usual (REST API call works like a charm: /api/v2/findings/27394 (173ms 2.85ms))

**Deployment method** *(select with an `X`)*
Kubernetes with helm chart

**Environment information**
DefectDojo v2.13.1
PostgreSQL 13
Google Kubernetes Engine
```yaml
celery:
  beat:
    replicas: 3
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 256Mi
  worker:
    replicas: 3
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 512Mi
django:
  nginx:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 256Mi
  replicas: 4
  uwsgi:
    resources:
      requests:
        cpu: 2000m
        memory: 8G
      limits:
        cpu: 2000m
        memory: 8G
    app_settings:
      processes: 2
      threads: 2
extraConfigs:
  DD_UWSGI_BUFFER_SIZE: '1048576' # 1MB
```

**Logs** 
Error from GCP Cloud logging:
nginx: GET /finding/27394 HTTP/1.1" 499
uwsgi: uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /finding/27394

**Sample scan files**
-

**Screenshots**
https://files.slack.com/files-pri/T04T40NHX-F047CAZMA73/502-server-error.png

**Additional context** (optional)
Total rows in our dojo_finding table 133630, dojo_engagement 5634, dojo_test 71158
