### ISSUE TITLE
Helm chart failing when trying to use a custom database

### ISSUE THREAD

**Issue by magmax** [DefectDojo/django-DefectDojo#7974]
**Bug description**
In order to use a custom deployed database, we set both `postgresql.enabled` and `mysql.enabled` to `false` breaking the whole helm chart.

After debugging a little bit, we realize the problem is in the `DD_DATABASE_*` keywords in the `configmap.yaml` file, which conditionally call to different macros but, with conditions set to false it finally returns an empty string which breaks the yaml specification.

**Steps to reproduce**
1. In an empty directory, create the file `Chart.yaml` with this content:
    ```
    apiVersion: v2
    appVersion: "2.20.3"
    description: test
    name: defectdojo-test
    version: 1.6.61
    
    dependencies:
      - name: defectdojo
        version: "1.6.61"
        repository: "https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts"
    ```
  
1. run `helm dep up .` to resolve dependencies.
1. create a file `values.yaml` with this content:
    ```
    defectdojo:           
      postgresql:         
        enabled: false    
      database: postgresql
    ```
1. these values will break it as well:
    ```
    defectdojo:           
      mysql:         
        enabled: false    
      database: mysql
    ```
1. try to get the yaml: `helm template .`

Result:
```
Error: YAML parse error on defectdojo-test/charts/defectdojo/templates/configmap.yaml: error converting YAML to JSON: yaml: line 30: found character that cannot start any token
```

**Expected behavior**
Yaml should not fail, and there should be an alternate way to allow us to define a custom database parameters.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo helm chart: 1.6.61

**Logs** 
N/A

**Sample scan files**
N/A

**Screenshots**
N/A

**Additional context** (optional)
using helm:
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

I offer myself to fix it... but I'd like to know your mind about the best way to specify the custom database parameters. I'd suggest using `.Values.custom_database.hostname` and so on... What do you think?

**Comment by sgrzemski** [comment]
Nope, use something like this:
```yaml
database: postgresql
postgresql:
  enabled: false
  postgresServer: "postgres.domain.com"
```
