### ISSUE TITLE
Installation hangs in Mysql using podman-compose

### ISSUE THREAD

**Issue by brunomcuesta** [DefectDojo/django-DefectDojo#8821]
Hello!
I'm trying to install defectdojo with podman-compose, but when building the containers an interruption related to Mysql occurs.

The `podman-compose build `command runs normally. The problem is in the `podman-compose up `command.

The first errors occur in relation to host and ports:

> podman start -a django-defectdojo_uwsgi_1
> Error: you need to provide a host and port to test.

> podman start -a django-defectdojo_initializer_1
> Error: you need to provide a host and port to test.

> podman start -a django-defectdojo_celeryworker_1
> Error: you need to provide a host and port to test.

> podman start -a django-defectdojo_celerybeat_1
> Error: you need to provide a host and port to test.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/2595cece-fde5-4c9d-ac8e-8bbc6ce1d990)

And after these errors it freezes on this Mysql line.

> Version: '5.7.43'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/ac555731-4237-4040-b18f-8b91f367d6bd)

**OS:** Ubuntu 22.04.3 LTS (Jammy Jellyfish)
**Podman Version**: 4.6.2
**podman-compose version**: 1.0.6

How can I solve this problem to install using podman-compose?
Thanks!

**Comment by mtesauro** [comment]
@brunomcuesta  As far as I am aware, none of the usual contributors use podman / podman-compose so I'm not sure anyone has experience who's a regular contributor.

I would suggest you consider switching to PostgreSQL instead of MySQL. PostgreSQL has much better test coverage and we're considering dropping MySQL as a supported DB in the future.

**Comment by brunomcuesta** [comment]
Hello!
Thanks for the answer.
Unfortunately, there are problems installing DefectDojo with podman-compose.
Docker cannot be used in companies without paying. Podman is an open-source alternative that has been growing in number of users.
I think it would be interesting if there was a podman-compose.yml ready to be able to install DefectDojo.
Thanks!

**Comment by mtesauro** [comment]
@brunomcuesta  I'm familiar with podman and have wanted to experiment with it. I just haven't had the spare time to actually spend any real time with podman.

My mention of PostgreSQL was that since podman appears to have issues with MySQL, PostgreSQL might "just work" and from a using DefectDojo perspective, the DB isn't super important. I do think that PostgreSQL scales better than MySQL - or at least it has in my experience.

The other thing that might be causing issues with Podman is that there are many ENV variables that are used by DefectDojo through the docker-compose yaml file. I'm wondering if those are not getting set based on the errors you shared above.

About podman-compose: I suspect the community will produce something like that over time. If you get something working, I'd be happy to have it in the [community-contrib repo](https://github.com/DefectDojo/Community-Contribs) for others to use.

**Comment by brunomcuesta** [comment]
Hello @mtesauro !
I have these two images on my Podman Desktop.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/97f70c24-a592-4835-986c-0121fe6a62f5)

Would it be possible to create from this point a container that runs DefectDojo with Postgres? Using the project's .sh scripts would not be possible, because they run docker-compose with the `--profile` parameter.
Thanks!

**Comment by mtesauro** [comment]
@brunomcuesta Take a look at this much more streamlined deployment: https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

Specifically, I'd start with this compose:  https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/docker-compose.yml
and then:
* Copy in the PostgreSQL lines from the compose in the main repo
* Swap out RabbitMQ with Redis (I've had more luck with Redis than RabbitMQ)

With the newly created compose, try podman-compose.

Best of luck.

**Comment by brunomcuesta** [comment]
Thank you for your help @mtesauro.
I checked the links you provided. I made some basic changes to the file.
I removed the profiles and calls to RabbitMQ from docker-compose.yml and now I get an error that I'm not sure where it comes from. It seems to be something related to mounting the django-defectdojo_defectdojo_media volume.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/834ee4c0-3883-42bf-9cb0-9737c1019492)

But the volume is created.

`podman volume inspect django-defectdojo_defectdojo_media`

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/67dac613-bb68-46b6-8eb6-c5490e679322)

This is my docker-compose.yml.

```
---
version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: "Dockerfile.nginx-${DEFECT_DOJO_OS:-debian}"
    image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}"
    depends_on:
      - uwsgi
    environment:
      NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media
    ports:
      - target: 8080
        published: ${DD_PORT:-8080}
        protocol: tcp
        mode: host
      - target: 8443
        published: ${DD_TLS_PORT:-8443}
        protocol: tcp
        mode: host
  uwsgi:
    build:
      context: ./
      dockerfile: "Dockerfile.django-${DEFECT_DOJO_OS:-debian}"
      target: django
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
    entrypoint: ['${DD_DATABASE_HOST}:${DD_DATABASE_PORT}','/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_DJANGO_METRICS_ENABLED: "${DD_DJANGO_METRICS_ENABLED:-False}"
      DD_ALLOWED_HOSTS: "${DD_ALLOWED_HOSTS:-*}"
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
  celerybeat:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
      - ${DD_DOCKERCOMPOSE_BROKER:-redis}
    entrypoint: ['${DD_DATABASE_HOST}:${DD_DATABASE_PORT}','/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
  celeryworker:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
      - ${DD_DOCKERCOMPOSE_BROKER:-redis}
    entrypoint: ['${DD_DATABASE_HOST}:${DD_DATABASE_PORT}','/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
  initializer:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
    entrypoint: ['${DD_DATABASE_HOST}:${DD_DATABASE_PORT}','/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
      DD_ADMIN_MAIL: "${DD_ADMIN_USER:-admin@defectdojo.local}"
      DD_ADMIN_FIRST_NAME: "${DD_ADMIN_FIRST_NAME:-Admin}"
      DD_ADMIN_LAST_NAME: "${DD_ADMIN_LAST_NAME:-User}"
      DD_INITIALIZE: "${DD_INITIALIZE:-true}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
  postgres:
    image: postgres:16.0-alpine@sha256:2ccd6655060d7b06c71f86094e8c7a28bdcc8a80b43baca4b1dabb29cff138a2
    environment:
      POSTGRES_DB: ${DD_DATABASE_NAME}
      POSTGRES_USER: ${DD_DATABASE_USER}
      POSTGRES_PASSWORD: ${DD_DATABASE_PASSWORD}
    volumes:
      - defectdojo_postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.2.1-alpine@sha256:9150d86fe2a9d03bbdb15bb9758fa5e3d24632386af8f6eb4d675ee4c976f499
    volumes:
      - defectdojo_redis:/data
volumes:
  defectdojo_media: {}
  defectdojo_redis: {}
  defectdojo_postgres: {}

```

Could it be a bug?
Thanks!
