### ISSUE TITLE
Overriding default values of dependent Redis chart not working

### ISSUE THREAD

**Issue by dkoci** [DefectDojo/django-DefectDojo#9713]
I would like to override `global.compatibility.openshift.adaptSecurityContext` default value of dependent Redis helm chart. I added
```yaml
redis:
  enabled: true
  global:
    compatibility:
      openshift:
        adaptSecurityContext: auto
```
to the defectdojo values.yaml file. But all values except `enabled: true` are not considered.
How can I override some of default values of dependent Redis chart?

Thank you
